version: '2'
services:
# service maven install container
 service_maven_install:
  build:
   context: ./rates-service
   dockerfile: ./Dockerfile
  image: rates_service_boot
  networks:
    demo_net:
      ipv4_address: 172.25.0.20

# ui maven install container
 ui_maven_install:
  build:
    context: ./rates-ui
    dockerfile: ./Dockerfile
  image: rates_ui_boot
  networks:
    demo_net:
      ipv4_address: 172.25.0.21

 eureka.server:
  image: netflixoss/eureka:1.3.1
  networks:
    demo_net:
      ipv4_address: 172.25.0.2
  ports:
   - "8761:8080"

 service1.application.start:
    image: rates_service_boot
    networks:
      demo_net:
        ipv4_address: 172.25.0.3
    ports:
      - "8091:8081"
    command:
      sh -c 'java -Deureka.environment=docker -jar /usr/src/app/target/rates-service-0.0.1-SNAPSHOT.jar'
    links:
      - eureka.server
    depends_on:
      - service_maven_install

 service2.application.start:
     image: rates_service_boot
     networks:
        demo_net:
          ipv4_address: 172.25.0.4
     ports:
       - "8093:8081"
     command:
       sh -c 'java -Deureka.environment=docker -jar /usr/src/app/target/rates-service-0.0.1-SNAPSHOT.jar'
     links:
       - eureka.server
     depends_on:
       - service_maven_install

 service3.application.start:
      image: rates_service_boot
      networks:
        demo_net:
          ipv4_address: 172.25.0.5
      ports:
        - "8094:8081"
      command:
        sh -c 'java -Deureka.environment=docker -jar /usr/src/app/target/rates-service-0.0.1-SNAPSHOT.jar'
      links:
        - eureka.server
      depends_on:
        - service_maven_install

 ui.application.start:
    image: rates_ui_boot
    networks:
      demo_net:
        ipv4_address: 172.25.0.6
    ports:
      - "8092:8082"
    command:
      sh -c 'java -Deureka.environment=docker -Dspring.profiles.active=docker -jar /usr/src/app/target/rates-ui-0.0.1-SNAPSHOT.jar'
    links:
      - service1.application.start
      - service2.application.start
      - service3.application.start
      - eureka.server
    depends_on:
      - service1.application.start
      - service2.application.start
      - service3.application.start
      - ui_maven_install

networks:
  demo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24